version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: mutation-analyzer-nginx
    volumes:
      - ./infra/nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - UWSGI_PORT=${UWSGI_PORT}
    networks:
      - mutation-analyzer-network
    depends_on:
      - app
  app:
    build: .
    entrypoint: bash entrypoint.sh
    image: mutation-analyzer-app
    container_name: mutation-analyzer-app
    volumes:
      - .:/var/www
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    networks:
      - mutation-analyzer-network
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: mutation-analyzer-postgres
    volumes:
      - ./infra/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mutation-analyzer-network

networks:
  mutation-analyzer-network:
    driver: bridge